// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs_XUMsgBjtZ6cnWWGVE8kd9t1Ca5jzoY',
    appId: '1:656341896992:web:1b94efd5cc1ceb06325145',
    messagingSenderId: '656341896992',
    projectId: 'sacred-songs-solos',
    authDomain: 'sacred-songs-solos.firebaseapp.com',
    databaseURL: 'https://sacred-songs-solos.firebaseio.com',
    storageBucket: 'sacred-songs-solos.appspot.com',
    measurementId: 'G-3SGRM0LR2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANDOzNIFlcJXm-_SGox2iL13qHUUzpHKQ',
    appId: '1:656341896992:android:828034c5a411bc7a325145',
    messagingSenderId: '656341896992',
    projectId: 'sacred-songs-solos',
    databaseURL: 'https://sacred-songs-solos.firebaseio.com',
    storageBucket: 'sacred-songs-solos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARbINFjN8PdTW1vOvYI-1BXpgTse2Vhj0',
    appId: '1:656341896992:ios:fffd23b1b073441a325145',
    messagingSenderId: '656341896992',
    projectId: 'sacred-songs-solos',
    databaseURL: 'https://sacred-songs-solos.firebaseio.com',
    storageBucket: 'sacred-songs-solos.appspot.com',
    iosClientId: '656341896992-gfsk0n9ht2ad285usb8dmg6bv2jq8eop.apps.googleusercontent.com',
    iosBundleId: 'com.hymnestry.hymnBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARbINFjN8PdTW1vOvYI-1BXpgTse2Vhj0',
    appId: '1:656341896992:ios:fffd23b1b073441a325145',
    messagingSenderId: '656341896992',
    projectId: 'sacred-songs-solos',
    databaseURL: 'https://sacred-songs-solos.firebaseio.com',
    storageBucket: 'sacred-songs-solos.appspot.com',
    iosClientId: '656341896992-gfsk0n9ht2ad285usb8dmg6bv2jq8eop.apps.googleusercontent.com',
    iosBundleId: 'com.hymnestry.hymnBook',
  );
}
